---
# Configuration file
# Change settings here to control how your box is set up.

# Git settings
git_name: "Your name"
git_email: "your@email.com"

# Vagrantfile configuration
boxipaddress: "192.168.200.200"
boxname: "vagrant"
memory: 1024

# Set the level of verbosity that Ansible will use
# This can be one of "", "v", "vv", "vvv", or "vvvv"
ansible_verbosity: ""