---
- name: apt-get | apt-get update
  apt: update_cache=yes
  tags: aptget
  sudo: true

- name: apt-get | ensure core packages are installed
  apt: pkg={{ item }} state=installed
  tags: aptget
  sudo: true
  with_items:
    - atool
    - atop
    - curl
    - git
    - make
    - tig
    - tree
    - vim
    - unzip
